name: 'K8s NetworkPolicy Verification'
description: 'An action to annotate a PR with connectivity compliance checks, based on preset policies'
author: 'shift-left-netconfig project'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        path: new
    - name: Baseline requirements validation
      uses: docker://ghcr.io/shift-left-netconfig/baseline-rules-verifier:1.1
      with:
        args: -b /baseline-rules-verifier/baseline-rules/examples/restrict_access_to_payment.yaml -b /baseline-rules-verifier/baseline-rules/examples/ciso_denied_ports.yaml -r /github/workspace/new/release /github/workspace/new/release --pr_url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments --tmp_dir /tmp --gh_token ${{ github.token }} --nca_path /nca
 
