name: K8s NetworkPolicy Verification
description: An action to verify connectivity compliance requirements, based on preset policies
author: shift-left-netconfig project

inputs:
  corporate-policies:
    description: A space-separated list of corporate policy files to verify (either as GitHub URL or path under GitHub workspace)
    required: true
  deployment-path:
    description: The path in GitHub workspace where deployment yamls are
    required: false
    default: .
  netpol-path:
    description: The path in GitHub workspace where the NetworkPolicy yamls are stored
    required: false
    default: .
  output-format:
    description: The format in which to output verifitaion results (either "md" or "txt")
    required: false
    default: md

outputs:
  policy-results-artifact:
    description: The name of the artifact containing verification results of all policies
    value: ${{ steps.output-results.outputs.policy-results-artifact }}
  policy-results-file:
    description: The name of the actual file in the artifact, which contain verification results for all policies
    value: ${{ steps.output-results.outputs.policy-results-file-name }}

runs:
  using: composite
  steps:
    - shell: sh
      run: |
        mkdir -p ${{ github.workspace }}/netpol-verify-gh-action-output
        chmod a+rw ${{ github.workspace }}/netpol-verify-gh-action-output
    - name: Prepare command-line arguments
      id: add-b-flag
      shell: bash
      run: |
        for policy in ${{ inputs.corporate-policies }}
        do
          export POLICIES_WITH_B="-b $policy $POLICIES_WITH_B"
        done
        echo "::set-output name=policies-with-b::$(echo $POLICIES_WITH_B)"
    - name: Baseline requirements validation
      uses: docker://ghcr.io/shift-left-netconfig/baseline-rules-verifier:1.3.1
      with:
        args: >
          ${{ steps.add-b-flag.outputs.policies-with-b }}
          -r /github/workspace/${{ inputs.deployment-path }}
          /github/workspace/${{ inputs.netpol-path }}
          --tmp_dir /tmp
          --nca_path /nca
          --format ${{ inputs.output-format }}
          -o /github/workspace/netpol-verify-gh-action-output/netpol-verify-output.${{ inputs.output-format }}
          --return_0
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: connectivity-policy-results
        path: ${{ github.workspace }}/netpol-verify-gh-action-output/netpol-verify-output.${{ inputs.output-format }}
    - name: Set output and clean
      id: output-results
      shell: bash
      run: |
        echo "::set-output name=policy-results-artifact::connectivity-policy-results"
        echo "::set-output name=policy-results-file-name::netpol-verify-output.${{ inputs.output-format }}"
        rm -r netpol-verify-gh-action-output
