name: K8s NetworkPolicy Verification
description: An action to annotate a PR with connectivity compliance checks, based on preset policies
author: shift-left-netconfig project

inputs:
  corporate-policies:
    description: A space-separated list of corporate policy files to verify (either as GitHub URL or path under GitHub workspace)
    required: true
  deployment-path:
    description: The path in GitHub workspace where deployment yamls are
    required: false
    default: .
  netpol-path:
    description: The path in GitHub workspace where the NetworkPolicy yamls are stored
    required: false
    default: .
  output-format:
    description: The format in which to output verifitaion results (either "md" or "txt")
    required: false
    default: md

outputs:
  rule-results:
    description: Verification results of all policies (as text)
    value: ${{ steps.output-results.outputs.verif-results }}

runs:
  using: composite
  steps:
    - shell: sh
      run: |
        mkdir -p ${{ github.workspace }}/output
        chmod a+rw ${{ github.workspace }}/output
    - name: Prepare command-line arguments
      id: add-b-flag
      shell: bash
      run: |
        for policy in ${{ inputs.corporate-policies }}
        do
          export POLICIES_WITH_B="-b $policy $POLICIES_WITH_B"
        done
        echo "::set-output name=policies-with-b::$(echo $POLICIES_WITH_B)"
    - name: Baseline requirements validation
      uses: docker://ghcr.io/shift-left-netconfig/baseline-rules-verifier:1.3.0
      with:
        args: >
          ${{ steps.add-b-flag.outputs.policies-with-b }}
          -r /github/workspace/${{ inputs.deployment-path }}
          /github/workspace/${{ inputs.netpol-path }}
          --tmp_dir /tmp
          --nca_path /nca
          --format ${{ inputs.output-format }}
          -o /github/workspace/output/netpol-verify-output.md
          --return_0
    - name: Set output
      id: output-results
      shell: bash
      run: |
        printf "$( cat ${{ github.workspace }}/output/netpol-verify-output.md )\n"
        printf "::set-output name=verif-results::$( cat ${{ github.workspace }}/output/netpol-verify-output.md )"
